SELECT * FROM GradeDetails
GO

ALTER TABLE GradeDetails
ADD CONSTRAINT DF_ACHIVEMENT_MAX_POINTS
DEFAULT 100 FOR AchievementMaxPoints
GO

ALTER TABLE GradeDetails WITH CHECK
ADD CONSTRAINT CHK_ACHIEVMENT_MAX_POINTS
CHECK(AchievementPoints <= AchievementMaxPoints)
GO

ALTER TABLE AchievementType
ADD CONSTRAINT UNQ_NAME
UNIQUE (Name)
GO